// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense.sql

package db

import (
	"context"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (title, amount)
VALUES ($1, $2)
RETURNING id, title, amount, created_at, updated_at
`

type CreateExpenseParams struct {
	Title  string
	Amount float64
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense, arg.Title, arg.Amount)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getAllExpenses = `-- name: GetAllExpenses :many
SELECT id, title, amount, created_at, updated_at 
FROM expenses
ORDER BY id DESC
`

func (q *Queries) GetAllExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getAllExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, title, amount, created_at, updated_at 
FROM expenses
WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id int32) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET 
  title = $2,
  amount = $3
WHERE 
  id = $1
RETURNING id, title, amount, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID     int32
	Title  string
	Amount float64
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense, arg.ID, arg.Title, arg.Amount)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
