// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID        int32
	Title     string
	Amount    float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
