CREATE TABLE expenses (
  id SERIAL PRIMARY KEY,
  title VARCHAR(50) NOT NULL, 
  amount DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);